apiVersion: v1
kind: service
metadata:
  name: sample-web-app-service
  namespace: argocd-test
  labels:
    app: sample-web-app
spec:
  selector:
    app: sample-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP